# Generated by Django 5.1.2 on 2024-11-02 15:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('capabilities', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='core_agentt_name_d0ecd0_idx')],
            },
        ),
        migrations.CreateModel(
            name='AgentInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('IDLE', 'Idle'), ('SHOPPING', 'Shopping'), ('VERIFYING', 'Verifying'), ('COMPLETED', 'Completed'), ('ERROR', 'Error')], default='IDLE', max_length=20)),
                ('trust_score', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('constraints', models.JSONField(default=dict)),
                ('max_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('allowed_merchants', models.JSONField(default=list)),
                ('bridge_wallet_address', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.agenttemplate')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('merchant', models.CharField(max_length=255)),
                ('merchant_wallet', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFYING', 'Verifying'), ('APPROVED', 'Approved'), ('EXECUTED', 'Executed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('market_average_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('lowest_price_found', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('price_difference_percentage', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executed_at', models.DateTimeField(null=True)),
                ('transaction_hash', models.CharField(blank=True, max_length=255)),
                ('agent_instance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.agentinstance')),
            ],
        ),
        migrations.CreateModel(
            name='PriceComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('url', models.URLField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.transaction')),
            ],
        ),
        migrations.AddIndex(
            model_name='agentinstance',
            index=models.Index(fields=['user', 'status'], name='core_agenti_user_id_2d1df4_idx'),
        ),
        migrations.AddIndex(
            model_name='agentinstance',
            index=models.Index(fields=['trust_score'], name='core_agenti_trust_s_1f0b8e_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['agent_instance', 'status'], name='core_transa_agent_i_1f7114_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['created_at'], name='core_transa_created_2964c5_idx'),
        ),
    ]
